mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("scoring.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts-django/", include("django.contrib.auth.urls")),
]

scoring/urls.py
from django.urls import path

from . import views

app_name = "scoring"
urlpatterns = [
    path("", views.index, name="index"),
    path("profile/", views.profile, name="profile"),
    path("edit_games/", views.edit_games, name="edit_games"),
    path("add_game/", views.add_game, name="add_game"),
    path("edit_game/<str:game_name>/", views.edit_game, name="edit_game"),
    path("delete_game/<str:game_name>/", views.delete_game, name="delete_game"),
    path("add_board", views.add_board, name="add_board"),
    path(
        "add_board_players/<str:game_name_or_board_pk>/",
        views.add_board_players,
        name="add_board_players",
    ),
    path("boards_list/", views.boards_list, name="boards_list"),
    path("delete_board/<int:board_pk>/", views.delete_board, name="delete_board"),
    path("board_score/<int:board_pk>/", views.board_score, name="board_score"),
    path("add_your_score/<int:board_pk>/", views.add_your_score, name="add_your_score"),
]

scoring/forms.py
from django import forms

from .models import Board, Game, Player, Scorer, ScoringCategory

# ----------
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Player
        exclude = ["user", "role"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "textinput form-control"
            field.widget.attrs["placeholder"] = field_name


# ----------
class AddGameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "textinput form-control"
            field.widget.attrs["placeholder"] = field_name

    def clean(self):
        cleaned_data = super().clean()

        # Check if the same game already exists in the DB.
        clean_name = Game.get_clean_name(cleaned_data["name"])
        game = Game.objects.filter(name=clean_name).first()
        if game:
            self.add_error("name", f"Game already exists as {clean_name}.")

        return cleaned_data


# ----------
_ScoringCategoryFormSet = forms.inlineformset_factory(Game, ScoringCategory, fields=["name"])


def __scoring_category_formset_is_valid(formset, *args, **kwargs):
    # Only keep forms with data: this can be undesired when emptying existing values
    # (meaning leaving blank a value that previously had data) must be forbidden, but
    # I want to allow it to delete an existing scoring category by just leaving it as
    # an empty field.
    formset.forms = [form for form in formset if form["name"].value()]
    return super(_ScoringCategoryFormSet, formset).is_valid(*args, **kwargs)


_ScoringCategoryFormSet.is_valid = __scoring_category_formset_is_valid


def get_scoring_category_formset(game: Game, post_data = None):
    if post_data is None:
        formset = _ScoringCategoryFormSet(instance=game)
    else:
        formset = _ScoringCategoryFormSet(post_data, instance=game)
    # Add styling
    for form in formset:
        for field_name, field in form.fields.items():
            if field_name == "DELETE":
                field.widget = forms.HiddenInput()
            else:
                field.widget.attrs["class"] = "textinput form-control"
                field.widget.attrs["placeholder"] = field_name
    return formset


# ----------
_AddScorersFormSet = forms.inlineformset_factory(Board, Scorer, fields=["name"])


def __add_scorers_formset_is_valid(formset, *args, **kwargs):
    forms_with_name = []
    for form in formset:
        if not form["name"].value():
            if form.instance.pk is not None:
                form.instance.delete()
            continue
        forms_with_name.append(form)
    formset.forms = forms_with_name
    return super(_AddScorersFormSet, formset).is_valid(*args, **kwargs)


_AddScorersFormSet.is_valid = __add_scorers_formset_is_valid


def get_add_scorers_formset(board: Board, post_data = None):
    if post_data is None:
        formset = _AddScorersFormSet(instance=board)
    else:
        formset = _AddScorersFormSet(post_data, instance=board)
    # Add styling
    for form in formset:
        for field_name, field in form.fields.items():
            if field_name == "DELETE":
                field.widget = forms.HiddenInput()
            else:
                field.widget.attrs["class"] = "textinput form-control"
                field.widget.attrs["placeholder"] = field_name
    return formset


# ----------
def add_your_scores_form_factory(form_name: str, sc_names: list[str]):
    form_fields = {
            "name": forms.CharField(max_length=50, label="Your name"),
        }
    score_fields = {
        scoring_category: forms.IntegerField(label=scoring_category)
        for scoring_category in sc_names
    }
    form_fields.update(score_fields)
    Form = type(
        form_name,
        (forms.Form,),
        form_fields.copy(),  # If I dont provide a copy then the dict is mutated within.
    )

    def form_init(self, *args, **kwargs):
        super(Form, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "textinput form-control"
            field.widget.attrs["placeholder"] = field_name

    Form.__init__ = form_init

    return Form

scoring/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse
from django.views.decorators.http import require_POST

from .forms import (
    AddGameForm,
    get_add_scorers_formset,
    ProfileForm,
    get_scoring_category_formset,
    add_your_scores_form_factory,
)
from .models import Board, Game, Player, Score, Scorer, ScoringCategory


def index(request: HttpRequest):
    if request.user.is_authenticated:
        if not hasattr(request.user, "player"):
            return HttpResponseRedirect(reverse("scoring:profile"))

    template = loader.get_template("scoring/index.html")
    context = {"games": Game.objects.all()}
    return HttpResponse(template.render(context, request))


@login_required
def profile(request: HttpRequest):
    # If the user doesn't have yet a player, we need to create one now.
    player = getattr(request.user, "player", None)
    if not player:
        player = Player(displayname=request.user.username, user=request.user)
        player.save()

    if request.method == "POST":
        form = ProfileForm(request.POST)
        try:
            a = form.is_valid()
        except Exception as exc:
            print(exc)
        if form.is_valid():
            displayname = form.cleaned_data["displayname"]
            player.displayname = displayname
            player.save()
            messages.success(
                request,
                f"Successfully updated profile for username: {request.user.username}."
                f" New displayname: {player.displayname}."
            )
            return HttpResponseRedirect(reverse("scoring:index"))
    else:  # GET
        form = ProfileForm(instance=player)

    # This return is not in the else because it will render errors for the POST case.
    context = {
        "form": form,
    }
    return render(request, "scoring/profile.html", context)


@login_required
def edit_games(request: HttpRequest):
    template = loader.get_template("scoring/edit_games.html")
    context = {"games": Game.objects.all()}
    return HttpResponse(template.render(context, request))


@login_required
def add_game(request: HttpRequest):
    if request.method == "POST":
        form = AddGameForm(request.POST)
        if form.is_valid():
            game = Game(name=form.cleaned_data["name"])
            game.save()
            return HttpResponseRedirect(reverse("scoring:edit_game", args=(game.name,)))

    else:
        form = AddGameForm()

    context = {
        "form": form,
    }
    return render(request, "scoring/add_game.html", context)


@login_required
def edit_game(request: HttpRequest, game_name: str):
    clean_game_name = Game.get_clean_name(game_name)
    game = Game.objects.filter(name=clean_game_name).first()
    if not game:
        messages.error(request, f"Game {game_name} not found.")
        return HttpResponseRedirect(reverse("scoring:index"))

    if request.method == "POST":
        # formset = ScoringCategoryFormSet(request.POST, instance=game)
        formset = get_scoring_category_formset(
            game=game,
            post_data=request.POST,
        )
        if formset.is_valid():
            game.scoringcategory_set.all().delete()
            for form in formset:
                if "name" not in form.cleaned_data:
                    continue
                sc_name = form.cleaned_data["name"]
                sc = ScoringCategory(
                    game=game,
                    name=sc_name,
                )
                sc.save()

            if request.POST.get("save_and_add_more"):
                return HttpResponseRedirect(
                    reverse("scoring:edit_game", args=(game_name,))
                )
            else:  # save_and_exit
                return HttpResponseRedirect(reverse("scoring:index"))

    else: # GET
        formset = get_scoring_category_formset(game=game)

    context = {
        "game_name": game_name,
        "formset": formset,
    }

    return render(
        request,
        "scoring/edit_game.html",
        context,
    )


@login_required
@require_POST
def delete_game(request: HttpRequest, game_name: str):
    clean_game_name = Game.get_clean_name(game_name)
    Game.objects.filter(name=clean_game_name).delete()
    return HttpResponseRedirect(reverse("scoring:edit_games"))


@login_required
def add_board(request: HttpRequest):
    template = loader.get_template(f"scoring/add_board.html")
    context = {"games": Game.objects.all()}
    return HttpResponse(template.render(context, request))


@login_required
def add_board_players(request: HttpRequest, game_name_or_board_pk: str):
    try:
        # Case where board_pk is passed: editing an existing board.
        board_pk = int(game_name_or_board_pk)
        board = get_object_or_404(Board, pk=board_pk)
        game = board.game
    except ValueError as exc:
        # Case where game_name is passed: creating a new board.
        game_name = game_name_or_board_pk
        clean_game_name = Game.get_clean_name(game_name)
        game = Game.objects.filter(name=clean_game_name).first()
        board = Board(game=game, player=request.user.player)

    if not game:
        messages.error(request, f"Game {game_name} not found.")
        return HttpResponseRedirect(reverse("scoring:index"))

    if request.method == "POST":
        if board.pk is None:
            # A new board is being created
            board.save()
        game = board.game
        formset = get_add_scorers_formset(board=board, post_data=request.POST)
        if formset.is_valid():
            # Create a new board:
            for form in formset:
                if "name" not in form.cleaned_data:
                    continue
                scorer: Scorer = form.instance
                scorer.save()

            if request.POST.get("save_and_add_more"):
                return HttpResponseRedirect(
                    reverse("scoring:add_board_players", args=(str(board.pk),))
                )
            else:  # save_and_exit
                return HttpResponseRedirect(
                    reverse("scoring:board_score", args=(str(board.pk),))
                )

    else:  # GET
        formset = get_add_scorers_formset(board=board)

    context = {
        "game_name": game.name,
        "game_name_or_board_pk": game_name_or_board_pk,  # needed for the form action
        "formset": formset,
    }

    return render(
        request,
        "scoring/add_board_players.html",
        context,
    )


@login_required
def boards_list(request: HttpRequest):
    player = request.user.player
    boards = player.board_set.all()
    context = {
        "boards": boards,
    }
    template = loader.get_template("scoring/boards_list.html")
    return HttpResponse(template.render(context, request))


@login_required
def board_score(request: HttpRequest, board_pk: int):
    board = get_object_or_404(Board, pk=board_pk)

    if request.method == "POST":
        score_keys = (key for key in request.POST if key.startswith("score"))
        for score_key in score_keys:
            score_key_parts = score_key.split("-")
            scoring_category_pk = int(score_key_parts[1])
            scorer_pk = int(score_key_parts[2])
            score = Score.objects.filter(
                board_id=board_pk,
                scorer_id=scorer_pk,
                scoring_category_id=scoring_category_pk,
            ).first()
            if score is None:
                score = Score(
                    board_id=board_pk,
                    scorer_id=scorer_pk,
                    scoring_category_id=scoring_category_pk,
                    value=0,
                )
            value_str = request.POST[score_key]
            if value_str:
                value = int(value_str)
            else:
                value = 0
            score.value = value
            score.save()
        return HttpResponseRedirect(reverse("scoring:board_score", args=(board_pk,)))

    game = board.game
    scoring_categories = game.scoringcategory_set.all()
    scorers = board.scorer_set.all()
    template = loader.get_template(f"scoring/board_score.html")
    score_values = {}
    totals = {}
    for scorer in scorers:
        score_values[scorer.pk] = {}
        totals[scorer.pk] = 0
        for scoring_category in scoring_categories:
            score_key = f"score-{scoring_category.pk}-{scorer.pk}"
            score = Score.objects.filter(
                board_id=board_pk,
                scoring_category_id=scoring_category.pk,
                scorer_id=scorer.pk,
            ).first()
            if score:
                score_value = score.value
            else:
                score_value = 0
            score_values[scorer.pk][scoring_category.pk] = score_value
            totals[scorer.pk] += score_value
    context = {
        "board": board,
        "game": game,
        "scoring_categories": scoring_categories,
        "scorers": scorers,
        "has_scorers": len(scorers) > 0,
        "score_values": score_values,
        "totals": totals,
        "url_share": request.build_absolute_uri(reverse("scoring:add_your_score", args=(board.pk,))),
    }
    return HttpResponse(template.render(context, request))


@login_required
@require_POST
def delete_board(request: HttpRequest, board_pk: int):
    board = get_object_or_404(Board, pk=board_pk)
    board.delete()
    messages.info(request, f"Board {board_pk} deleted.")
    return HttpResponseRedirect(reverse("scoring:boards_list"))


def add_your_score(request: HttpRequest, board_pk: int):
    # TODO: create links with a jwt token with expiration so it's easy to reject
    # requests after 5 min. Also make sure to only allow a maximum number of scorers
    # per board to avoid attacks.

scoring/templates/scoring/add_board.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-1">
  {% comment %}
    TODO: Make this into a form, and after clicking the board is created so the user can be redirected
    to the board already and share it instead of passing through the step of adding players, which is now
    optional because the board is shareable so people can add their own scores.
  {% endcomment %}
  <h2>Select game:</h2>
  <div class="list-group">
    {% for game in games %}
    <a
      href="{% url 'scoring:add_board_players' game.name %}"
      class="list-group-item list-group-item-action">
        {{ game.name }}
    </a>
    {% endfor %}
  </div>

</div>
{% endblock content %}

scoring/templates/scoring/add_board_players.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}
  <link rel="stylesheet" type="text/css" href="{% static 'scoring/css/forms.css' %}" />
{% endblock extra_head %}

{% block content %}
<div class="text-center">
  <div class="form-signin">
    <h1 class="h3 mb-0 fw-normal">Add Board Players:</h1>
    <p class="small-text mb-3">(...and remove players by leaving names blank)</p>
    <form
      action="{% url 'scoring:add_board_players' game_name_or_board_pk %}"
      method="post"
    >
      {% csrf_token %}
      {{ formset.management_form }}
      {% for form in formset %}
        {{ form.non_field_errors }}
          {% for field in form %}
            <div id="div_{{ field.auto_id }}" class="form-floating mb-3">
              {{ field.errors }}
              {{ field }}
              {% if field.widget_type != 'hidden' %}
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {% endif %}
            </div>
        {% endfor %}
      {% endfor %}
      <div class="form-actions">
        <input
          type="submit"
          name="save_and_add_more"
          value="Save and add more"
          class="btn btn-primary w-100 btn btn-lg"
          id="submit-id-save_and_add_more"
        >
        <input
          type="submit"
          name="save_and_exit"
          value="Save and exit"
          class="btn btn-primary w-100 btn btn-lg"
          id="submit-id-save_and_exit"
        >
      </div>
    </form>
  </div>
{% endblock content %}

scoring/templates/scoring/add_game.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}
  <link rel="stylesheet" type="text/css" href="{% static 'scoring/css/forms.css' %}" />
{% endblock extra_head %}

{% block content %}
<div class="text-center">
  <div class="form-signin">
    <h1 class="h3 mb-3 fw-normal">Add game:</h1>
    <form action="{% url 'scoring:add_game' %}" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
      <div id="div_{{ field.auto_id }}" class="form-floating mb-3">
        {{ field.errors }}
        {{ field }}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      </div>
      {% endfor %}
      <div class="mb-3">
        <div class="form-floating">
          <input
            type="submit"
            name="save"
            value="Save"
            class="btn btn-primary w-100 btn btn-lg btn-primary"
            id="submit-id-save"
          >
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

scoring/templates/scoring/add_your_score.html
{% extends "base.html" %}

{% block content %}
<div class="text-center">
  <div class="form-signin">
    <h1 class="h3 mb-3 fw-normal">Add your name and scores: {{ game_name }}</h1>
    <form action="{% url 'scoring:add_your_score' board_pk %}" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
      <div id="div_{{ field.auto_id }}" class="form-floating mb-3">
        {{ field.errors }}
        {{ field }}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      </div>
      {% endfor %}
      <div class="mb-3">
        <div class="form-floating">
          <input
            type="submit"
            name="save"
            value="Save"
            class="btn btn-primary w-100 btn btn-lg btn-primary"
            id="submit-id-save"
          >
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

scoring/templates/scoring/board_score.html
{% extends "base.html" %}
{% load static %}
{% load get_from_dict %}

{% block extra_head %}
  <link rel="stylesheet" type="text/css" href="{% static 'scoring/css/board_score.css' %}" />
  <script>
    function CopyText() {
      var text = document.getElementById('yourtext')
      text.select();
      document.execCommand('copy')
    }
  </script>
{% endblock extra_head %}

{% block content %}

<div class="text-center container">
  <h1 class="h3 mb-0 fw-normal">Board #{{ board.pk }} for game {{ game.name }}</h1>
  {% if not has_scorers %}
    <p>Seems like there are no players yet, add them yourself or share the board with them so they can add their own scores!</p>
  {% endif %}
</div>

{% if has_scorers %}
  <div class="text-center mt-2">
    <form action="{% url "scoring:board_score" board.pk %}" method="post">
      <!-- CSRF toke tag for POST forms targeted at internal urls. -->
      {% csrf_token %}
      <fieldset>
        <!-- Display error message if any. -->
        {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
        {% endif %}
        <!-- Show list of choices. -->
        <table class="table">
          <thead>
            <tr>
              <th scope="col"></th>
              {% for scorer in scorers %}
                <th scope="col" class="scorer-label">{{ scorer.display_name }}</th>
              {% endfor %}
            </tr>
          </thead>
          <tbody>
            {% comment %} Rows for scoring categories score values {% endcomment %}
            {% for scoring_category in scoring_categories %}
            <tr>
              <th scope="row" class="scoring-category-label">{{ scoring_category.name }}</th>
              {% for scorer in scorers %}
              <th scope="row">
                <div class="score-container d-flex justify-content-center">
                  <input
                    type="number"
                    name="score-{{ scoring_category.pk }}-{{ scorer.pk }}"
                    id="score-{{ scoring_category.pk }}-{{ scorer.pk }}"
                    value="{{ score_values|get_from_dict:scorer.pk|get_from_dict:scoring_category.pk }}",
                  />
                </div>
              </th>
              {% endfor %}
            </tr>
            {% endfor %}
            {% comment %} Row for totals {% endcomment %}
            <tr>
              <th scope="row" class="scoring-category-label">Total</th>
              {% for scorer in scorers %}
              <th scope="row">
                <div class="score-container d-flex justify-content-center">
                  <input
                    type="number"
                    disabled
                    name="score-total-{{ scorer.pk }}"
                    id="score-total-{{ scorer.pk }}"
                    value="{{ totals|get_from_dict:scorer.pk }}",
                  />
                </div>
              </th>
              {% endfor %}
            </tr>
          </tbody>
        </table>
      </fieldset>
      <button
        value="Save"
        class="btn btn-primary btn-lg w-50"
        >
          Save
        </button>
    </form>
  </div>
{% endif %}

<div class="text-center mt-3">
  <a href="{% url "scoring:add_board_players" board.pk %}">
    <button
      type="button"
      class="btn btn-success btn-lg w-50"
      data-bs-toggle="modal"
      data-bs-target="#deleteBoardModal"
    >
      Edit Board Players
    </button>
  </a>
</div>

<div class="text-center mt-2">
  <!-- Button trigger modal -->
  <button
    type="button"
    class="btn btn-success btn btn-lg mt-0 w-50"
    data-bs-toggle="modal"
    data-bs-target="#shareModal"
  >
    Share
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="shareModal" tabindex="-1" aria-labelledby="shareModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="shareModalLabel">Share with friends:</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Share this link with friends and they can add their own scores</p>
        <p>(they don't need to be registered for this)</p>
        <input class="textinput form-control" type="text" value="{{ url_share }}" id="yourtext">
        <button class="btn btn-primary" onclick="CopyText()">Copy Link</button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Button trigger modal -->
<div class="text-center mt-3">
  <button
    type="button"
    class="btn btn-danger w-50"
    data-bs-toggle="modal"
    data-bs-target="#deleteBoardModal"
  >
    Delete Board
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteBoardModal" tabindex="-1" aria-labelledby="deleteBoardModalLabel" aria-hidden="true">
  <form action="{% url 'scoring:delete_board' board.pk %}" method="post">
    {% csrf_token %}
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteBoardModalLabel">Delete Board {{ board.pk }}</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Are  you sure you want to delete this board?</p>
          <p>This operation is not reversible!</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button name="delete_board" class="btn btn-danger">Delete</button>
        </div>
      </div>
    </div>
  </form>
</div>

{% endblock %}

scoring/templates/scoring/boards_list.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-1">

  <h2>Your boards:</h2>
  <div class="list-group">
    {% for board in boards %}
    <a
      href="{% url "scoring:board_score" board.pk %}"
      class="list-group-item list-group-item-action"
    >
        Board #{{ board.pk }} ({{ board.game.name }})
    </a>
    {% endfor %}
  </div>

</div>
{% endblock content %}

scoring/templates/scoring/edit_game.html
{% extends "base.html" %}
{% load static %}
{% load dummy_filter %}

{% block extra_head %}
  <link rel="stylesheet" type="text/css" href="{% static 'scoring/css/forms.css' %}" />
{% endblock extra_head %}

{% block content %}
<div class="text-center">
  <div class="form-signin">
    <h1 class="h3 mb-3 fw-normal">Edit game: {{ game_name }}</h1>
    <form action="{% url 'scoring:edit_game' game_name %}" method="post">
      {% csrf_token %}
      {{ formset.management_form }}
      {% for form in formset %}
        {{ form.non_field_errors }}
          {% for field in form %}
            <div id="div_{{ field.auto_id }}" class="form-floating mb-3">
              {{ field.errors }}
              {{ field }}
              {% if field.widget_type != 'hidden' %}
                <label for="{{ field.id_for_label }}">Scoring category</label>
              {% endif %}
            </div>
        {% endfor %}
      {% endfor %}
      <div class="form-actions">
        <input
          type="submit"
          name="save_and_add_more"
          value="Save and add more"
          class="btn btn-primary w-100 btn btn-lg btn-primary"
          id="submit-id-save_and_add_more"
        >
        <input
          type="submit"
          name="save_and_exit"
          value="Save and exit"
          class="btn btn-primary w-100 btn btn-lg btn-primary"
          id="submit-id-save_and_exit"
        >
      </div>
    </form>
  </div>

  <!-- Button trigger modal -->
  <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteGameModal">
    Delete Game
  </button>

  <!-- Modal -->
  <div class="modal fade" id="deleteGameModal" tabindex="-1" aria-labelledby="deleteGameModalLabel" aria-hidden="true">
    <form action="{% url 'scoring:delete_game' game_name %}" method="post">
      {% csrf_token %}
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteGameModalLabel">Delete Game {{ game_name }}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>Are  you sure you want to delete this game?</p>
            <p>This operation is not reversible!</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button name="delete_game" class="btn btn-danger">Delete</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

scoring/templates/scoring/edit_games.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-1">

  <div class="text-center">
    <h1 class="h3 mb-3 fw-normal">Edit games:</h1>
    <div class="list-group">
      {% for game in games %}
      <a
        href="{% url 'scoring:edit_game' game.name %}"
        class="list-group-item list-group-item-action">
          {{ game.name }}
      </a>
      {% endfor %}
    </div>
  </div>


</div>
{% endblock content %}

scoring/templates/scoring/index.html
{% extends "base.html" %}
{% load static %}

{% block extra_head %}
  <link rel="stylesheet" type="text/css" href="{% static 'scoring/css/index.css' %}" />
{% endblock extra_head %}

{% block content %}
<div class="container mt-1">
  <div class="buttons-container">
    <a href="{% url "scoring:boards_list" %}">
      <button class="btn btn-primary w-100" type="button">See Scores</button>
    </a>
    <a href="{% url "scoring:add_board" %}">
      <button class="btn btn-primary mt-3 w-100" type="button">Start New Score</button>
    </a>
  </div>
</div>
{% endblock content %}

scoring/templates/scoring/profile.html
{% extends "base.html" %}

{% block content %}
<div class="text-center">
  <div class="form-signin">
    <h1 class="h3 mb-3 fw-normal">Player profile:</h1>
    <form action="{% url 'scoring:profile' %}" method="post">
      {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
      <div id="div_{{ field.auto_id }}" class="form-floating mb-3">
        {{ field.errors }}
        {{ field }}
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
      </div>
      {% endfor %}
      <div class="mb-3">
        <div class="form-floating">
          <input
            type="submit"
            name="save"
            value="Save"
            class="btn btn-primary w-100 btn btn-lg btn-primary"
            id="submit-id-save"
          >
        </div>
      </div>
    </form>
  </div>
</div>

<div class="wip container text-center">
  <p>
    Work in progress: this page will contain the full player profile with a displayable name accross the app, a
    description and other personal data. Maybe here they can also modify their email.
    And also show the favourite games of the player, as well as the current and past boards
    that they are in, with links to each scoring board.
  </p>
</div>
{% endblock content %}