accounts/urls.py
from django.urls import path

from . import views

app_name = "accounts"
urlpatterns = [
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("invite/", views.invite, name="invite"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("scoring.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts-django/", include("django.contrib.auth.urls")),
]

scoring/urls.py
from django.urls import path

from . import views

app_name = "scoring"
urlpatterns = [
    path("", views.index, name="index"),
    path("profile/", views.profile, name="profile"),
    path("edit_games/", views.edit_games, name="edit_games"),
    path("add_game/", views.add_game, name="add_game"),
    path("edit_game/<str:game_name>/", views.edit_game, name="edit_game"),
    path("delete_game/<str:game_name>/", views.delete_game, name="delete_game"),
    path("add_board", views.add_board, name="add_board"),
    path(
        "add_board_players/<str:game_name_or_board_pk>/",
        views.add_board_players,
        name="add_board_players",
    ),
    path("boards_list/", views.boards_list, name="boards_list"),
    path("delete_board/<int:board_pk>/", views.delete_board, name="delete_board"),
    path("board_score/<int:board_pk>/", views.board_score, name="board_score"),
    path("add_your_score/<int:board_pk>/", views.add_your_score, name="add_your_score"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="A web app to keep track of scoring for board games.">
  <meta name="keywords" content="boardgames,scoring">
    <title>
      {% block title %}Scoring App{% endblock title %}
    </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% bootstrap_messages %}
    {% block extra_head %}
    {% endblock extra_head %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'scoring:index' %}">
          Home
        </a>
        <div class="d-flex">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if request.user.is_anonymous %}
              <li class="nav-item">
                <a class="nav-link ms-1"
                    aria-current="page"
                    href="{% url 'accounts:login' %}">Login</a>
              </li>
            {% else %}
              {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                  <button
                    type="button"
                    class="btn btn-light dropdown-toggle ms-1"
                    data-bs-toggle="dropdown"
                    aria-expanded="false"
                  >
                    {{ request.user.player.displayname }}
                  </button>
                  <ul class="dropdown-menu dropdown-menu-end position-absolute" aria-labelledby="navbarDropdown">
                    <li class="nav-item">
                      {% if request.user.player.is_editor %}
                        <a
                          class="dropdown-item"
                          href="{% url 'scoring:add_game' %}"
                        >
                          Add New Game
                        </a>
                      </li>
                      <li class="nav-item">
                        <a
                          class="dropdown-item"
                          href="{% url 'scoring:edit_games' %}"
                        >
                          Edit Games
                        </a>
                      </li>
                    {% endif %}  <!-- is_editor -->
                    <li><hr class="dropdown-divider"></li>
                    <li class="nav-item">
                      <a
                        class="dropdown-item"
                        href="{% url 'scoring:profile' %}"
                      >
                        Profile
                      </a>
                    </li>
                    <li class="nav-item">
                      <a
                        class="dropdown-item"
                        href="{% url 'accounts:invite' %}"
                      >
                        Invite friends
                      </a>
                    </li>
                    <li class="nav-item">
                      <a
                        class="dropdown-item"
                        href="{% url 'accounts:logout' %}"
                      >
                        Log out
                      </a>
                    </li>
                  </ul>
                </li>
              {% endif %} <!-- is_authenticated  -->
            {% endif %} <!-- is_anonymous -->
          </ul>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}
  </body>
</html>